// src/components/FloatingActionButton.tsx
'use client';

import React from 'react';

interface FloatingActionButtonProps {
  show: boolean;
  count: number;
  onClick: () => void;
}

export default function FloatingActionButton({ show, count, onClick }: FloatingActionButtonProps) {
  if (!show) return null;

  return (
    <button
      onClick={onClick}
      className="fixed bottom-8 right-8 bg-primary text-white rounded-full p-4 shadow-xl hover:shadow-2xl transition-all hover:-translate-y-1 transform z-40 group"
    >
      <div className="flex items-center gap-3">
        <div className="relative">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
          {count > 0 && (
            <span className="absolute -top-2 -right-2 bg-white text-primary text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center">
              {count}
            </span>
          )}
        </div>
        <span className="pr-2">Review Selection</span>
      </div>
    </button>
  );
}

// components/FloatingActionButton.vue
<template>
  <Transition
    enter-active-class="transition duration-200 ease-out"
    enter-from-class="transform translate-y-10 opacity-0"
    enter-to-class="transform translate-y-0 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="transform translate-y-0 opacity-100"
    leave-to-class="transform translate-y-10 opacity-0"
  >
    <div 
      v-if="show && count > 0"
      class="fixed md:right-8 md:bottom-8 md:w-auto w-full px-4 bottom-0 z-40"
    >
      <div 
        class="bg-white md:rounded-2xl shadow-2xl shadow-primary/10 p-4 md:p-6 flex items-center justify-between gap-4 md:gap-6"
        :class="{'rounded-none': isMobile}"
      >
        <div class="flex items-center gap-3">
          <div class="bg-primary/10 text-primary rounded-full w-10 h-10 flex items-center justify-center font-bold">
            {{ count }}
          </div>
          <div class="text-left">
            <p class="text-secondary font-medium">{{ count }} {{ count === 1 ? 'Activity' : 'Activities' }} Selected</p>
            <p class="text-sm text-secondary/70">Click to complete your proposal</p>
          </div>
        </div>
        <button
          @click="$emit('click')"
          class="bg-primary text-white px-6 py-3 rounded-xl hover:bg-primary/90 transition-colors flex items-center gap-2"
        >
          Continue
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>
    </div>
  </Transition>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useWindowSize } from '@vueuse/core'

const props = defineProps<{
  show: boolean
  count: number
}>()

defineEmits<{
  click: []
}>()

const { width } = useWindowSize()
const isMobile = computed(() => width.value < 768)
</script>
