// src/components/ProposalModal.tsx
interface FormData {
  name: string;
  email: string;
  company: string;
  message?: string;
}

interface ProposalModalProps {
  show: boolean;
  selectedActivities: string[];
  onClose: () => void;
  onSubmit: (data: FormData) => Promise<void>;
  isSubmitting?: boolean;
}

export default function ProposalModal({ 
  show, 
  selectedActivities, 
  onClose, 
  onSubmit,
  isSubmitting = false 
}: ProposalModalProps) {
  if (!show) return null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-auto shadow-2xl">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold text-secondary">Complete Your Proposal</h2>
            <button
              onClick={onClose}
              className="text-secondary/50 hover:text-secondary transition-colors disabled:opacity-50"
              disabled={isSubmitting}
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        <div className="p-6">
          <div className="space-y-6">
            <div>
              <h3 className="font-medium text-secondary mb-2">Selected Activities</h3>
              <div className="flex flex-wrap gap-2">
                {selectedActivities.map((activity) => (
                  <div
                    key={activity}
                    className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm"
                  >
                    {activity}
                  </div>
                ))}
              </div>
            </div>

            <form onSubmit={async (e) => {
              e.preventDefault();
              const formData = new FormData(e.currentTarget);
              const data: FormData = {
                name: formData.get('name') as string,
                email: formData.get('email') as string,
                company: formData.get('company') as string,
                message: formData.get('message') as string || undefined
              };
              await onSubmit(data);
            }}>
              <div className="space-y-4">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-secondary mb-1">
                    Your Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    required
                    disabled={isSubmitting}
                    className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary disabled:opacity-50 disabled:bg-gray-50"
                  />
                </div>

                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-secondary mb-1">
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    required
                    disabled={isSubmitting}
                    className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary disabled:opacity-50 disabled:bg-gray-50"
                  />
                </div>

                <div>
                  <label htmlFor="company" className="block text-sm font-medium text-secondary mb-1">
                    Company Name
                  </label>
                  <input
                    type="text"
                    id="company"
                    name="company"
                    required
                    disabled={isSubmitting}
                    className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary disabled:opacity-50 disabled:bg-gray-50"
                  />
                </div>

                <div>
                  <label htmlFor="message" className="block text-sm font-medium text-secondary mb-1">
                    Additional Notes
                  </label>
                  <textarea
                    id="message"
                    name="message"
                    rows={4}
                    disabled={isSubmitting}
                    className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary disabled:opacity-50 disabled:bg-gray-50"
                  ></textarea>
                </div>
              </div>

              <div className="mt-6 flex justify-end gap-4">
                <button
                  type="button"
                  onClick={onClose}
                  disabled={isSubmitting}
                  className="px-6 py-2 rounded-xl border border-gray-200 text-secondary hover:bg-gray-50 transition-colors disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-6 py-2 rounded-xl bg-primary text-white hover:bg-primary/90 transition-colors disabled:opacity-50 flex items-center gap-2"
                >
                  {isSubmitting ? (
                    <>
                      <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Submitting...
                    </>
                  ) : (
                    'Submit Proposal'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

// components/ProposalModal.vue
<template>
  <TransitionRoot appear :show="show" as="template">
    <Dialog as="div" @close="close" class="relative z-50">
      <TransitionChild
        as="template"
        enter="duration-300 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-200 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-secondary/30 backdrop-blur-sm" />
      </TransitionChild>

      <div class="fixed inset-0 overflow-y-auto">
        <div class="flex min-h-full items-center justify-center p-4 text-center">
          <TransitionChild
            as="template"
            enter="duration-300 ease-out"
            enter-from="opacity-0 scale-95"
            enter-to="opacity-100 scale-100"
            leave="duration-200 ease-in"
            leave-from="opacity-100 scale-100"
            leave-to="opacity-0 scale-95"
          >
            <DialogPanel class="w-full max-w-2xl transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all relative">
              <!-- Success Message Overlay -->
              <TransitionChild
                as="div"
                enter="duration-300 ease-out"
                enter-from="opacity-0 scale-95"
                enter-to="opacity-100 scale-100"
                leave="duration-200 ease-in"
                leave-from="opacity-100 scale-100"
                leave-to="opacity-0 scale-95"
              >
                <div v-if="isSuccess" class="absolute inset-0 bg-white flex items-center justify-center flex-col gap-4 z-50">
                  <div class="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-primary" viewBox="0 0 20 20" fill="currentColor">
                      <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <div class="text-center">
                    <h3 class="text-xl font-bold text-secondary mb-2">Proposal Submitted!</h3>
                    <p class="text-secondary/70">We'll get back to you shortly.</p>
                  </div>
                </div>
              </TransitionChild>

              <DialogTitle as="h3" class="font-display text-2xl font-bold text-secondary mb-4">
                Complete Your Team Building Proposal
              </DialogTitle>

              <div class="space-y-6">
                <!-- Selected Activities -->
                <div v-if="selectedActivities.length > 0" class="space-y-6">
                  <div class="bg-secondary-light rounded-xl p-4">
                    <h4 class="font-display text-lg font-bold text-secondary mb-3">Selected Activities</h4>
                    <TransitionGroup 
                      tag="ul" 
                      class="space-y-2"
                      enter-active-class="transition duration-300 ease-out"
                      enter-from-class="opacity-0 -translate-x-4"
                      enter-to-class="opacity-100 translate-x-0"
                      leave-active-class="transition duration-200 ease-in"
                      leave-from-class="opacity-100 translate-x-0"
                      leave-to-class="opacity-0 translate-x-4"
                    >
                      <li 
                        v-for="activity in selectedActivities" 
                        :key="activity" 
                        class="flex items-center gap-2 text-secondary/70 bg-white/50 px-3 py-2 rounded-lg"
                      >
                        <span class="text-primary">✓</span>
                        {{ activity }}
                      </li>
                    </TransitionGroup>
                  </div>
                </div>

                <!-- Contact Form -->
                <form @submit.prevent="handleSubmit" class="space-y-4">
                  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div class="space-y-2">
                      <label for="name" class="block text-sm font-medium text-secondary">Full Name</label>
                      <input 
                        type="text" 
                        id="name" 
                        v-model="form.name"
                        required
                        :disabled="isSubmitting"
                        class="w-full px-4 py-2 rounded-lg border border-secondary/20 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                      />
                    </div>

                    <div class="space-y-2">
                      <label for="email" class="block text-sm font-medium text-secondary">Work Email</label>
                      <input 
                        type="email" 
                        id="email" 
                        v-model="form.email"
                        required
                        :disabled="isSubmitting"
                        class="w-full px-4 py-2 rounded-lg border border-secondary/20 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                      />
                    </div>

                    <div class="space-y-2">
                      <label for="city" class="block text-sm font-medium text-secondary">City</label>
                      <input 
                        type="text" 
                        id="city" 
                        v-model="form.city"
                        required
                        :disabled="isSubmitting"
                        class="w-full px-4 py-2 rounded-lg border border-secondary/20 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                      />
                    </div>

                    <div class="space-y-2">
                      <label for="groupSize" class="block text-sm font-medium text-secondary">Group Size</label>
                      <input 
                        type="number" 
                        id="groupSize" 
                        v-model="form.groupSize"
                        required
                        min="1"
                        :disabled="isSubmitting"
                        class="w-full px-4 py-2 rounded-lg border border-secondary/20 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                      />
                    </div>

                    <div class="space-y-2 md:col-span-2">
                      <label for="date" class="block text-sm font-medium text-secondary">Tentative Date</label>
                      <input 
                        type="date" 
                        id="date" 
                        v-model="form.date"
                        required
                        :disabled="isSubmitting"
                        class="w-full px-4 py-2 rounded-lg border border-secondary/20 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                      />
                    </div>
                  </div>

                  <div class="flex items-center justify-end gap-4 mt-6">
                    <button
                      type="button"
                      @click="close"
                      :disabled="isSubmitting"
                      class="px-6 py-2 rounded-lg text-secondary hover:bg-secondary-light transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      :disabled="isSubmitting"
                      class="px-6 py-2 rounded-lg bg-primary text-white hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                    >
                      <span v-if="isSubmitting" class="inline-block animate-spin w-4 h-4 border-2 border-white/20 border-t-white rounded-full"></span>
                      {{ isSubmitting ? 'Submitting...' : 'Submit Proposal' }}
                    </button>
                  </div>
                </form>
              </div>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import {
  TransitionRoot,
  TransitionChild,
  Dialog,
  DialogPanel,
  DialogTitle,
} from '@headlessui/vue'

const props = defineProps<{
  show: boolean
  selectedActivities: string[]
  isSubmitting?: boolean
  isSuccess?: boolean
}>()

const emit = defineEmits<{
  close: []
  submit: [formData: any]
}>()

const form = ref({
  name: '',
  email: '',
  city: '',
  groupSize: '',
  date: ''
})

const handleSubmit = () => {
  emit('submit', form.value)
}

const close = () => {
  if (!props.isSubmitting) {
    emit('close')
  }
}
</script>
